[package]
name = "slack-rust"
version = "0.1.0"
authors = ["Gompei <shoueigonpei6028@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
async-tungstenite = "0.15.0"
async-tls = "0.11.0"
surf = "2.3.1"
serde =  { version = "1.0.130", features = ["derive"] }
serde_json = "1.0"
url = "2.2"
